/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import cli.Console;
import command.CommandFactory;
import command.CommandInvoker;
import command.ICommand;
import hashtable.Hashtable;

import java.util.LinkedList;

public class Main {

    private static final String sProgramHeadline = "Hashtable example";

    public static void main(String[] args) {
        Console console = new Console();
        int size = 13;
        int doubleHashingPrime = 7;
        Hashtable hashtable = new Hashtable(size, doubleHashingPrime);
        LinkedList<ICommand> commands = CommandFactory.createAppCommendList(console, hashtable);
        CommandInvoker invoker = new CommandInvoker(commands, console, sProgramHeadline, true);
        invoker.run();
    }
}
